exports.userInfo = {
  id: 1,
  nome: 'João Cláudio',
  usuario: 'aspenstevens',
  senha: '123456',
  tokenAcesso: null,
  listas: [
    {
      id: 1,
      nomeLista: 'Chá de casa nova de Jan e Kaire',
      tipoLista: 'Chá de casa nova',
      qtdItensTotal: 0,
      qtdItensAssinados: 0,
      itens: [],
      config: {
        imagem: '',
        color1: '',
        color2: '',
        color3: '',
        titulo: '',
        mensagem: '',
      },
    },
    {
      id: 2,
      nomeLista: 'Chá de fralda de Henry',
      tipoLista: 'Chá de fralda',
      qtdItensTotal: 0,
      qtdItensAssinados: 0,
      itens: [],
      config: {
        imagem: '',
        color1: '',
        color2: '',
        color3: '',
        titulo: '',
        mensagem: '',
      },
    },
    {
      id: 3,
      nomeLista: 'Chá Missionário de Ryan',
      tipoLista: 'Chá Missionário',
      qtdItensTotal: 0,
      qtdItensAssinados: 0,
      itens: [],
      config: {
        imagem: '',
        color1: '',
        color2: '',
        color3: '',
        titulo: '',
        mensagem: '',
      },
    },
  ],
};
