/**
 * Paletas numeradas (1–30). Escolha com `VITE_THEME_VARIATION` no `.env`.
 * Cores em código JS (hex) — não sofrem da regra do `.env` em que `#` inicia comentário.
 */

/** @typedef {{ id: number; name: string; primary: string; accent: string; surface: string; backgroundA: string; backgroundB: string; text: string; textOnPrimary: string }} ThemePalette */

/** @type {ThemePalette[]} */
export const THEME_PALETTES = [
	{
		id: 1,
		name: 'Azul clássico',
		primary: '#1565c0',
		accent: '#90caf9',
		surface: '#ffffff',
		backgroundA: '#e3f2fd',
		backgroundB: '#ffffff',
		text: '#0d47a1',
		textOnPrimary: '#ffffff',
	},
	{
		id: 2,
		name: 'Verde natural',
		primary: '#2e7d32',
		accent: '#a5d6a7',
		surface: '#fafafa',
		backgroundA: '#e8f5e9',
		backgroundB: '#ffffff',
		text: '#1b5e20',
		textOnPrimary: '#ffffff',
	},
	{
		id: 3,
		name: 'Rosa chá',
		primary: '#c2185b',
		accent: '#f8bbd0',
		surface: '#fff5f8',
		backgroundA: '#fce4ec',
		backgroundB: '#ffffff',
		text: '#880e4f',
		textOnPrimary: '#ffffff',
	},
	{
		id: 4,
		name: 'Âmbar sol',
		primary: '#f9a825',
		accent: '#fff9c4',
		surface: '#fffde7',
		backgroundA: '#fff9c4',
		backgroundB: '#ffffff',
		text: '#4e342e',
		textOnPrimary: '#3e2723',
	},
	{
		id: 5,
		name: 'Terracota',
		primary: '#bf360c',
		accent: '#ffab91',
		surface: '#fff3e0',
		backgroundA: '#ffe0b2',
		backgroundB: '#fff8f5',
		text: '#3e2723',
		textOnPrimary: '#ffffff',
	},
	{
		id: 6,
		name: 'Lavanda',
		primary: '#5e35b1',
		accent: '#d1c4e9',
		surface: '#f3e5f5',
		backgroundA: '#e1bee7',
		backgroundB: '#ffffff',
		text: '#311b92',
		textOnPrimary: '#ffffff',
	},
	{
		id: 7,
		name: 'Menta',
		primary: '#00796b',
		accent: '#b2dfdb',
		surface: '#e0f2f1',
		backgroundA: '#b2ebf2',
		backgroundB: '#ffffff',
		text: '#004d40',
		textOnPrimary: '#ffffff',
	},
	{
		id: 8,
		name: 'Marinho',
		primary: '#0d47a1',
		accent: '#64b5f6',
		surface: '#eceff1',
		backgroundA: '#bbdefb',
		backgroundB: '#ffffff',
		text: '#01579b',
		textOnPrimary: '#ffffff',
	},
	{
		id: 9,
		name: 'Coral',
		primary: '#ff7043',
		accent: '#ffccbc',
		surface: '#fff8f5',
		backgroundA: '#ffe0b2',
		backgroundB: '#ffffff',
		text: '#bf360c',
		textOnPrimary: '#ffffff',
	},
	{
		id: 10,
		name: 'Sálvia',
		primary: '#558b2f',
		accent: '#c5e1a5',
		surface: '#f1f8e9',
		backgroundA: '#dcedc8',
		backgroundB: '#ffffff',
		text: '#33691e',
		textOnPrimary: '#ffffff',
	},
	{
		id: 11,
		name: 'Vinho',
		primary: '#880e4f',
		accent: '#f48fb1',
		surface: '#fce4ec',
		backgroundA: '#f8bbd0',
		backgroundB: '#ffffff',
		text: '#4a148c',
		textOnPrimary: '#ffffff',
	},
	{
		id: 12,
		name: 'Turquesa',
		primary: '#00838f',
		accent: '#80deea',
		surface: '#e0f7fa',
		backgroundA: '#b2ebf2',
		backgroundB: '#ffffff',
		text: '#006064',
		textOnPrimary: '#ffffff',
	},
	{
		id: 13,
		name: 'Pêssego',
		primary: '#ff8a65',
		accent: '#ffccbc',
		surface: '#fff8f5',
		backgroundA: '#ffe0b2',
		backgroundB: '#ffffff',
		text: '#5d4037',
		textOnPrimary: '#ffffff',
	},
	{
		id: 14,
		name: 'Grafite',
		primary: '#424242',
		accent: '#bdbdbd',
		surface: '#fafafa',
		backgroundA: '#eeeeee',
		backgroundB: '#ffffff',
		text: '#212121',
		textOnPrimary: '#ffffff',
	},
	{
		id: 15,
		name: 'Índigo',
		primary: '#303f9f',
		accent: '#9fa8da',
		surface: '#e8eaf6',
		backgroundA: '#c5cae9',
		backgroundB: '#ffffff',
		text: '#1a237e',
		textOnPrimary: '#ffffff',
	},
	{
		id: 16,
		name: 'Oliva',
		primary: '#827717',
		accent: '#d4e157',
		surface: '#f9fbe7',
		backgroundA: '#f0f4c3',
		backgroundB: '#ffffff',
		text: '#33691e',
		textOnPrimary: '#ffffff',
	},
	{
		id: 17,
		name: 'Chocolate & creme',
		primary: '#5d4037',
		accent: '#d7ccc8',
		surface: '#efebe9',
		backgroundA: '#d7ccc8',
		backgroundB: '#faf8f6',
		text: '#3e2723',
		textOnPrimary: '#fff8e1',
	},
	{
		id: 18,
		name: 'Lilás',
		primary: '#7b1fa2',
		accent: '#e1bee7',
		surface: '#f3e5f5',
		backgroundA: '#e1bee7',
		backgroundB: '#ffffff',
		text: '#4a148c',
		textOnPrimary: '#ffffff',
	},
	{
		id: 19,
		name: 'Teal profundo',
		primary: '#00695c',
		accent: '#4db6ac',
		surface: '#e0f2f1',
		backgroundA: '#b2dfdb',
		backgroundB: '#ffffff',
		text: '#004d40',
		textOnPrimary: '#ffffff',
	},
	{
		id: 20,
		name: 'Mostarda',
		primary: '#f57f17',
		accent: '#fff59d',
		surface: '#fffde7',
		backgroundA: '#fff9c4',
		backgroundB: '#ffffff',
		text: '#3e2723',
		textOnPrimary: '#212121',
	},
	{
		id: 21,
		name: 'Rosa pó',
		primary: '#ad1457',
		accent: '#f48fb1',
		surface: '#fce4ec',
		backgroundA: '#f8bbd0',
		backgroundB: '#ffffff',
		text: '#880e4f',
		textOnPrimary: '#ffffff',
	},
	{
		id: 22,
		name: 'Azul gelo',
		primary: '#0277bd',
		accent: '#b3e5fc',
		surface: '#e1f5fe',
		backgroundA: '#b3e5fc',
		backgroundB: '#ffffff',
		text: '#01579b',
		textOnPrimary: '#ffffff',
	},
	{
		id: 23,
		name: 'Floresta',
		primary: '#1b5e20',
		accent: '#81c784',
		surface: '#e8f5e9',
		backgroundA: '#c8e6c9',
		backgroundB: '#ffffff',
		text: '#0d3d11',
		textOnPrimary: '#ffffff',
	},
	{
		id: 24,
		name: 'Ameixa',
		primary: '#4a148c',
		accent: '#ce93d8',
		surface: '#ede7f6',
		backgroundA: '#d1c4e9',
		backgroundB: '#ffffff',
		text: '#311b92',
		textOnPrimary: '#ffffff',
	},
	{
		id: 25,
		name: 'Areia',
		primary: '#8d6e63',
		accent: '#d7ccc8',
		surface: '#faf8f5',
		backgroundA: '#efebe9',
		backgroundB: '#ffffff',
		text: '#3e2723',
		textOnPrimary: '#ffffff',
	},
	{
		id: 26,
		name: 'Oceano',
		primary: '#006064',
		accent: '#4dd0e1',
		surface: '#e0f7fa',
		backgroundA: '#b2ebf2',
		backgroundB: '#ffffff',
		text: '#004d40',
		textOnPrimary: '#ffffff',
	},
	{
		id: 27,
		name: 'Carmesim',
		primary: '#c62828',
		accent: '#ffcdd2',
		surface: '#ffebee',
		backgroundA: '#ffcdd2',
		backgroundB: '#ffffff',
		text: '#b71c1c',
		textOnPrimary: '#ffffff',
	},
	{
		id: 28,
		name: 'Eucalipto',
		primary: '#436858',
		accent: '#a8c5a8',
		surface: '#f0f4f0',
		backgroundA: '#d4e6d4',
		backgroundB: '#ffffff',
		text: '#2e3d35',
		textOnPrimary: '#ffffff',
	},
	{
		id: 29,
		name: 'Ardósia',
		primary: '#455a64',
		accent: '#b0bec5',
		surface: '#eceff1',
		backgroundA: '#cfd8dc',
		backgroundB: '#ffffff',
		text: '#263238',
		textOnPrimary: '#ffffff',
	},
	{
		id: 30,
		name: 'Púrpura real',
		primary: '#4527a0',
		accent: '#b39ddb',
		surface: '#ede7f6',
		backgroundA: '#d1c4e9',
		backgroundB: '#ffffff',
		text: '#311b92',
		textOnPrimary: '#ffffff',
	},
];

export const THEME_PALETTE_COUNT = THEME_PALETTES.length;

const BY_ID = Object.fromEntries(THEME_PALETTES.map((p) => [p.id, p]));

/**
 * @param {unknown} raw — típico: `import.meta.env.VITE_THEME_VARIATION` ("1"…"30")
 * @returns {ThemePalette}
 */
export function getThemePaletteForVariation(raw) {
	const n = Number.parseInt(String(raw ?? '').trim(), 10);
	const id =
		Number.isFinite(n) && n >= 1 && n <= THEME_PALETTE_COUNT
			? n
			: 1;
	return BY_ID[id] ?? THEME_PALETTES[0];
}

/**
 * Objeto de configuração indexado por id (1–30), útil para introspectão ou docs.
 * @type {Record<number, ThemePalette>}
 */
export const THEME_PALETTES_BY_ID = BY_ID;

/** Rótulo para selects (ex.: `3 — Rosa chá`). */
export function getThemeSelectOptionLabel(p) {
	return `${p.id} — ${p.name}`;
}
